modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="dronemod"
version="1.0.0"
displayName="Kamikaze Drones"
description="Plane-type drones that randomly dive onto big player builds and blow them up with fire."

[[dependencies.dronemod]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.dronemod]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"
